---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: construsalesman-proyectofinal4-trigger-template
spec:
  params:
    - name: repo-url
      description: The git repository URL to clone from.
    - name: tag-name
      description: The git tag to clone.
    - name: image-full-path-with-tag
      description: The image full path to host the built image, with version tag, e.g. image-registry.openshift-image-registry.svc:5000/tekton-pipelines/spring-boot-docker:v1.0.0.
    - name: deployment-script
      description: The script file for deployment.
    - name: maven-image
      description: The maven image to use for compile and build
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-deploy-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: cicd-deploy-tekton
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: tag-name
            value: $(tt.params.tag-name)
          - name: image-full-path-with-tag
            value: $(tt.params.image-full-path-with-tag)
          - name: deployment-script
            value: $(tt.params.deployment-script)
          - name: maven-image
            value: $(tt.params.maven-image)
        workspaces:
          - name: maven-settings
            configmap:
              name: maven-settings
          - name: workspace
            persistentvolumeclaim:
              claimName: shared-workspace
          - name: empty-dir
            emptyDir: {}
